#pragma once
/**
 * @file BehaviorSignal.h
 * @brief Behavioral signals tracked per character within a run to drive
 *        Stance crystallization. Incremented by Battle after each player action.
 */

enum class BehaviorSignal
{
    Aggressive,  ///< Heavy Basic and Arch Skill use relative to Slot Skills and Ultimate.
    Methodical,  ///< Slot Skills used frequently; Energy conserved before spending.
    Sacrificial, ///< Actions taken at high Exposure or low HP.
    Supportive,  ///< SP generated by this character exceeds personal SP spending.
    Reactive,    ///< Vent used frequently; Exposure kept consistently below 40.
};